import { MigrationInterface, QueryRunner } from "typeorm";

export class InicializarEstructuraCore1781837586179 implements MigrationInterface {
    name = 'InicializarEstructuraCore1781837586179'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "core_countries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "country_code" character varying(2) NOT NULL, "name" character varying(100) NOT NULL, "phone_code" character varying(5) NOT NULL, "currency_code" character varying(3) NOT NULL, CONSTRAINT "UQ_ebed2e4e3c101bd0192d899e4b5" UNIQUE ("name"), CONSTRAINT "PK_9074e45b7c98fa89aa3263044a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2a04726c6371212c91121735db" ON "core_countries"  ("country_code") `);
        await queryRunner.query(`CREATE TABLE "core_tenant_brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "logo_url" character varying(255), "favicon_url" character varying(255), "primary_color" character varying(30) NOT NULL DEFAULT '#4F46E5', "sidebar_bg_color" character varying(30) NOT NULL DEFAULT '#1F2937', "company_legal_name" character varying(100), "login_welcome_text" character varying(150), "tenant_id" uuid NOT NULL, CONSTRAINT "REL_976909f23c930fff1c974bf3b3" UNIQUE ("tenant_id"), CONSTRAINT "PK_2234b408c3f9be4014a484e39f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "subdomain" character varying(50) NOT NULL, "name" character varying(150) NOT NULL, "commercial_name" character varying(150), "tax_id" character varying(50) NOT NULL, "timezone" character varying(50) NOT NULL, "currency" character varying(3) NOT NULL, "plan_type" character varying(20) NOT NULL, "country_id" uuid, CONSTRAINT "UQ_39b9f2b4f7b61ad35eafaf6cdba" UNIQUE ("tax_id"), CONSTRAINT "PK_912a10c1e83d1f9c8e98a0d63af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6441a96352094a8ac9d74d5197" ON "core_tenants"  ("subdomain") `);
        await queryRunner.query(`CREATE TABLE "core_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(150), CONSTRAINT "PK_3ce6e3a8629aa4d65c4aed78837" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e7a3f78f0ba2b7517da06cd20" ON "core_users"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE TABLE "core_system_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "email" character varying(150) NOT NULL, "password_hash" character varying(255) NOT NULL, "user_id" uuid, CONSTRAINT "REL_9e22b1854842341decd9bf7c17" UNIQUE ("user_id"), CONSTRAINT "PK_f8cf2c8c1d2266e73450f425211" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6e6de0b11cc2d4e25998e027c" ON "core_system_accounts"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3035b3d5616ada1077e5e19d4c" ON "core_system_accounts"  ("email", "tenant_id") `);
        await queryRunner.query(`CREATE TABLE "core_tenant_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_component_id" uuid NOT NULL, "action" character varying(20) NOT NULL, "code" character varying(100) NOT NULL, "description" character varying(150), CONSTRAINT "UQ_1e0ce1b17605ee9cba2fe03c77d" UNIQUE ("code"), CONSTRAINT "PK_3fb0658fc06719813607e12998d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_tenant_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "code" character varying(50) NOT NULL, "description" character varying(255), CONSTRAINT "UQ_f9015bad2963c5c813b08b1e19c" UNIQUE ("name"), CONSTRAINT "UQ_b298c27bb6e92dd5aff4d8f532e" UNIQUE ("code"), CONSTRAINT "PK_b04911fd8d80c3791ef28255342" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core_tenant_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "is_system_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_cd267232b753c141227fbb01e4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_29c7d97da8ce58c8a8d947c8be" ON "core_tenant_roles"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE TABLE "core_tenant_role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "tenant_role_id" uuid NOT NULL, "tenant_permission_id" uuid NOT NULL, CONSTRAINT "PK_2247fb821d5e18c91bca998dad4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1e4cab15b3067f8f230758d061" ON "core_tenant_role_permissions"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_992c73dc8b0a5c75b3f9a34baa" ON "core_tenant_role_permissions"  ("tenant_id", "tenant_role_id", "tenant_permission_id") `);
        await queryRunner.query(`CREATE TABLE "core_tenant_user_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "tenant_permission_id" uuid NOT NULL, "is_granted" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c35ef181facfdd1bfa3575f2b60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_beb28bf0ce22bcd81ac8c9268f" ON "core_tenant_user_exceptions"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bd294b36f353a94fdb2edfa9cb" ON "core_tenant_user_exceptions"  ("tenant_id", "user_id", "tenant_permission_id") `);
        await queryRunner.query(`CREATE TABLE "core_tenant_user_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid, "user_id" uuid NOT NULL, "theme_mode" character varying(10) NOT NULL DEFAULT 'light', "default_landing_page" character varying(150), "ag_grid_state" jsonb, CONSTRAINT "UQ_eb4cac3d6c4548c23e50738e1bf" UNIQUE ("user_id"), CONSTRAINT "REL_eb4cac3d6c4548c23e50738e1b" UNIQUE ("user_id"), CONSTRAINT "PK_9ef143f8c6b91d4c7a840c3f701" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a9772f72598c60206b3cf40523" ON "core_tenant_user_preferences"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE TABLE "core_tenant_user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "tenant_role_id" uuid NOT NULL, CONSTRAINT "PK_2ee64b4ea7aea0f4ee6e31dbdd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9011cf00a86681d1436c24bbfb" ON "core_tenant_user_roles"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b2e5f1d142f48135f78efd11e" ON "core_tenant_user_roles"  ("tenant_id", "user_id", "tenant_role_id") `);
        await queryRunner.query(`CREATE TABLE "hcm_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid, "name" character varying(150) NOT NULL, CONSTRAINT "PK_b9dcdcde213b8d35744fdd85e5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_310edd380804f0d2d31636cae0" ON "hcm_areas"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2fcffc12d6e56b17a75d86c961" ON "hcm_areas"  ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "hcm_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid, "name" character varying(150) NOT NULL, CONSTRAINT "PK_f0db5101984fa2fdd95c8830cd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_386e124e1b1004ce75c5df709b" ON "hcm_jobs"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_230a061eb98a1aca3c425a2564" ON "hcm_jobs"  ("tenant_id", "name") `);
        await queryRunner.query(`CREATE TABLE "hcm_employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid, "employee_code" character varying(50) NOT NULL, "government_id" character varying(50) NOT NULL, "biological_sex" character varying(10) NOT NULL, "hire_date" date NOT NULL, "termination_date" date, "job_id" uuid NOT NULL, "area_id" uuid NOT NULL, "user_id" uuid, CONSTRAINT "REL_19fed47c8f00d76282a7933214" UNIQUE ("user_id"), CONSTRAINT "PK_cd47b3ed7a09cb31859d26df169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41ea793355745377dc7da374b9" ON "hcm_employees"  ("tenant_id", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f56b9c97690d11f6e879c468a4" ON "hcm_employees"  ("tenant_id", "government_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_670788ae859996633ad1304bd5" ON "hcm_employees"  ("tenant_id", "employee_code") `);
        await queryRunner.query(`ALTER TABLE "core_tenant_brands" ADD CONSTRAINT "FK_976909f23c930fff1c974bf3b38" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenants" ADD CONSTRAINT "FK_cc0cdfeb21476c4889eaaab5645" FOREIGN KEY ("country_id") REFERENCES "core_countries"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_users" ADD CONSTRAINT "FK_c0d0f2dc44bc285be7a97f9531c" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_system_accounts" ADD CONSTRAINT "FK_c477a06e2e1281c28959d99077f" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_system_accounts" ADD CONSTRAINT "FK_9e22b1854842341decd9bf7c17e" FOREIGN KEY ("user_id") REFERENCES "core_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_permissions" ADD CONSTRAINT "FK_4901a3418db0758230f074c0f88" FOREIGN KEY ("tenant_component_id") REFERENCES "core_tenant_components"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_roles" ADD CONSTRAINT "FK_4b26eab6097b8f964e4d6a172eb" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_role_permissions" ADD CONSTRAINT "FK_179a41835ab9fcfa97a975c7f4b" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_role_permissions" ADD CONSTRAINT "FK_634033b0d45a9a89520abef15df" FOREIGN KEY ("tenant_role_id") REFERENCES "core_tenant_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_role_permissions" ADD CONSTRAINT "FK_8ce5e81bc1524f4033e1ebf337e" FOREIGN KEY ("tenant_permission_id") REFERENCES "core_tenant_permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_exceptions" ADD CONSTRAINT "FK_122edc86610be21b458844ac488" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_exceptions" ADD CONSTRAINT "FK_12b15679cfec1c1aa7a68e50981" FOREIGN KEY ("user_id") REFERENCES "core_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_exceptions" ADD CONSTRAINT "FK_f24c63ed9e3d40d065a7c206794" FOREIGN KEY ("tenant_permission_id") REFERENCES "core_tenant_permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_preferences" ADD CONSTRAINT "FK_cea1d940d5fbf56f1f222508ce3" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_preferences" ADD CONSTRAINT "FK_eb4cac3d6c4548c23e50738e1bf" FOREIGN KEY ("user_id") REFERENCES "core_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_roles" ADD CONSTRAINT "FK_18421b774296c68eb2fda600353" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_roles" ADD CONSTRAINT "FK_b249fb0564e1672207c94af01dd" FOREIGN KEY ("user_id") REFERENCES "core_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_roles" ADD CONSTRAINT "FK_2bca11240a35774c83b9c636540" FOREIGN KEY ("tenant_role_id") REFERENCES "core_tenant_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hcm_areas" ADD CONSTRAINT "FK_0418416ca94b3d416361ad21fbd" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hcm_jobs" ADD CONSTRAINT "FK_fb9149600ae1dd088f2983d1b5e" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" ADD CONSTRAINT "FK_28adcf23a52cc8891c97e87d956" FOREIGN KEY ("tenant_id") REFERENCES "core_tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" ADD CONSTRAINT "FK_8d2c616c230b14048db24b0f0de" FOREIGN KEY ("job_id") REFERENCES "hcm_jobs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" ADD CONSTRAINT "FK_a049b1fca144335803c3cde3266" FOREIGN KEY ("area_id") REFERENCES "hcm_areas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" ADD CONSTRAINT "FK_19fed47c8f00d76282a79332145" FOREIGN KEY ("user_id") REFERENCES "core_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "hcm_employees" DROP CONSTRAINT "FK_19fed47c8f00d76282a79332145"`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" DROP CONSTRAINT "FK_a049b1fca144335803c3cde3266"`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" DROP CONSTRAINT "FK_8d2c616c230b14048db24b0f0de"`);
        await queryRunner.query(`ALTER TABLE "hcm_employees" DROP CONSTRAINT "FK_28adcf23a52cc8891c97e87d956"`);
        await queryRunner.query(`ALTER TABLE "hcm_jobs" DROP CONSTRAINT "FK_fb9149600ae1dd088f2983d1b5e"`);
        await queryRunner.query(`ALTER TABLE "hcm_areas" DROP CONSTRAINT "FK_0418416ca94b3d416361ad21fbd"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_roles" DROP CONSTRAINT "FK_2bca11240a35774c83b9c636540"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_roles" DROP CONSTRAINT "FK_b249fb0564e1672207c94af01dd"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_roles" DROP CONSTRAINT "FK_18421b774296c68eb2fda600353"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_preferences" DROP CONSTRAINT "FK_eb4cac3d6c4548c23e50738e1bf"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_preferences" DROP CONSTRAINT "FK_cea1d940d5fbf56f1f222508ce3"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_exceptions" DROP CONSTRAINT "FK_f24c63ed9e3d40d065a7c206794"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_exceptions" DROP CONSTRAINT "FK_12b15679cfec1c1aa7a68e50981"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_user_exceptions" DROP CONSTRAINT "FK_122edc86610be21b458844ac488"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_role_permissions" DROP CONSTRAINT "FK_8ce5e81bc1524f4033e1ebf337e"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_role_permissions" DROP CONSTRAINT "FK_634033b0d45a9a89520abef15df"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_role_permissions" DROP CONSTRAINT "FK_179a41835ab9fcfa97a975c7f4b"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_roles" DROP CONSTRAINT "FK_4b26eab6097b8f964e4d6a172eb"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_permissions" DROP CONSTRAINT "FK_4901a3418db0758230f074c0f88"`);
        await queryRunner.query(`ALTER TABLE "core_system_accounts" DROP CONSTRAINT "FK_9e22b1854842341decd9bf7c17e"`);
        await queryRunner.query(`ALTER TABLE "core_system_accounts" DROP CONSTRAINT "FK_c477a06e2e1281c28959d99077f"`);
        await queryRunner.query(`ALTER TABLE "core_users" DROP CONSTRAINT "FK_c0d0f2dc44bc285be7a97f9531c"`);
        await queryRunner.query(`ALTER TABLE "core_tenants" DROP CONSTRAINT "FK_cc0cdfeb21476c4889eaaab5645"`);
        await queryRunner.query(`ALTER TABLE "core_tenant_brands" DROP CONSTRAINT "FK_976909f23c930fff1c974bf3b38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_670788ae859996633ad1304bd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f56b9c97690d11f6e879c468a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ea793355745377dc7da374b9"`);
        await queryRunner.query(`DROP TABLE "hcm_employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_230a061eb98a1aca3c425a2564"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_386e124e1b1004ce75c5df709b"`);
        await queryRunner.query(`DROP TABLE "hcm_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fcffc12d6e56b17a75d86c961"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_310edd380804f0d2d31636cae0"`);
        await queryRunner.query(`DROP TABLE "hcm_areas"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b2e5f1d142f48135f78efd11e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9011cf00a86681d1436c24bbfb"`);
        await queryRunner.query(`DROP TABLE "core_tenant_user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9772f72598c60206b3cf40523"`);
        await queryRunner.query(`DROP TABLE "core_tenant_user_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd294b36f353a94fdb2edfa9cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_beb28bf0ce22bcd81ac8c9268f"`);
        await queryRunner.query(`DROP TABLE "core_tenant_user_exceptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_992c73dc8b0a5c75b3f9a34baa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e4cab15b3067f8f230758d061"`);
        await queryRunner.query(`DROP TABLE "core_tenant_role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_29c7d97da8ce58c8a8d947c8be"`);
        await queryRunner.query(`DROP TABLE "core_tenant_roles"`);
        await queryRunner.query(`DROP TABLE "core_tenant_components"`);
        await queryRunner.query(`DROP TABLE "core_tenant_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3035b3d5616ada1077e5e19d4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6e6de0b11cc2d4e25998e027c"`);
        await queryRunner.query(`DROP TABLE "core_system_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e7a3f78f0ba2b7517da06cd20"`);
        await queryRunner.query(`DROP TABLE "core_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6441a96352094a8ac9d74d5197"`);
        await queryRunner.query(`DROP TABLE "core_tenants"`);
        await queryRunner.query(`DROP TABLE "core_tenant_brands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a04726c6371212c91121735db"`);
        await queryRunner.query(`DROP TABLE "core_countries"`);
    }

}
